---
layout: post   
title:  " Node.js 예외처리 "
categories: Node.js
comments: true
tags: Node.js 예외처리
author: teddy8  
---
* content
{:toc}

```
Node.js에서 다음과 같은 예외처리 방법 2가지를 예제를 통해 정리한다.
1. 비동기(Async) 모듈, 콜백함수
2. try-catch, throw
```

## 비동기(Async) 모듈
example.js

``` js
"use strict";

const cbFunc = (err, result) => {   // cbFunc라는 콜백함수 정의
    if (err && err instanceof Error) // err에 값이 있으면서 Error객체면 console출력 후 return으로 함수 종료
        return console.error(err.message); 
    if (err) // err에 값이 있는데 Error 객체가 아닌 경우 console출력 후 return으로 함수 종료
        return console.error(err); 

    console.log('에러를 반환하지 않습니다');
};

const asyncFunction = (isTrue, callback) => {
    const err = new Error('This is error!!');

    if (isTrue)
        return callback(null, isTrue);
    else 
        return callback(err);
};

asyncFunction(true, cbFunc);
asyncFunction(false, cbFunc);
```

실행결과
```
에러를 반환하지 않습니다
This is error!!
```
```
 비동기 콜백함수 cbFunc를 정의한다
```

## try-catch, throw
example.js
``` js
"use strict";

const fs = require('fs');

try {
    const fileList = fs.readdirSync('/undefined/');
    console.log('hello');
    fileList.forEach(f => console.log(f));
} catch (err) {
    if (err) console.error(err);
}

```

실행결과
```
{ Error: ENOENT: no such file or directory, scandir 'c:\undefined'
    at Object.fs.readdirSync (fs.js:928:18)
    at Object.<anonymous> (c:\Program Files\Git\usr\practicejs\JSExerciseFiles\part4\166.js:27:25)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'c:\\undefined' }
```
```
```